name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: startup
        run: make startup_all